steps:
  # Pull the sweepai/sweep:latest image from Docker Hub (or wherever it resides)
  - name: 'docker'
    args: ['pull', 'sweepai/sweep:latest']

  # Tag the pulled image for Google Container Registry (GCR)
  - name: 'docker'
    args: ['tag', 'sweepai/sweep:latest', 'gcr.io/$PROJECT_ID/sweep:latest']

  # Push the image to GCR
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/sweep:latest']

  # Deploy the image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'beta',
      'run',
      'deploy',
      'develop-up-sweep', # Replace with your desired Cloud Run service name
      '--image', 'gcr.io/$PROJECT_ID/sweep:latest',
      '--region', 'us-central1', # Replace with your desired region
      '--platform', 'managed',
      '--memory', '8Gi',
      '--cpu', '4',
      '--allow-unauthenticated', # Remove this line if you want authentication
      '--port=8080',
      '--set-env-vars=APP_ID=387016,
        WEBHOOK_PROXY_URL=https://smee.io/EeGJ7GSiwztXCYNR,
        GITHUB_CLIENT_ID=Iv1.b8a073e931d1d7a3,
        OPENAI_DO_HAVE_32K_MODEL_ACCESS=false,
        SENTENCE_TRANSFORMERS_MODEL=sentence-transformers/all-MiniLM-L6-v2',
      '--set-secrets=GITHUB_APP_PEM=GITHUB_APP_PEM:latest,
        OPENAI_API_KEY=OPENAI_API_KEY:latest',
    ]


options:
  logging: CLOUD_LOGGING_ONLY
  env: ['PORT=8080']
