steps:
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/sweepai/sweep']

  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
    dir: 'sweep/self_deploy'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/upmortem-sweep']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'beta',
        'run',
        'deploy',
        'upmortem-sweep',
        '--image',
        'gcr.io/cloud-builders/gcloud',
        '--region',
        'us-central1',
        '--platform',
        'managed',
        '--min-instances=2',
      ]


options:
  env: ['PORT=3000']
  logging: CLOUD_LOGGING_ONLY
