steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/develop-up-sweep', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/develop-up-sweep']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'beta',
      'run',
      'deploy',
      'develop-up-sweep', # Replace with your desired Cloud Run service name
      '--image', 'gcr.io/$PROJECT_ID/develop-up-sweep',
      '--region', 'us-central1', # Replace with your desired region
      '--platform', 'managed',
      '--allow-unauthenticated', # Remove this line if you want authentication
      '--port=3000'
      '--set-env-vars=APP_ID=387016,
        WEBHOOK_PROXY_URL=https://smee.io/EeGJ7GSiwztXCYNR,
        GITHUB_CLIENT_ID=Iv1.b8a073e931d1d7a3,
        OPENAI_DO_HAVE_32K_MODEL_ACCESS=false,
        SENTENCE_TRANSFORMERS_MODEL=sentence-transformers/all-MiniLM-L6-v2',
      '--set-secrets=GITHUB_APP_PEM=GITHUB_APP_PEM:latest,
        OPENAI_API_KEY=OPENAI_API_KEY:latest',
    ]


options:
  logging: CLOUD_LOGGING_ONLY
  env: ['PORT=3000']
